export const METRIC_ID = {
  REVENUE: "revenue",
  GROSS_PROFIT: "gross_profit",
  GROSS_MARGIN: "gross_margin",
  OPERATING_INCOME: "operating_income",
  NET_INCOME: "net_income",
  OPERATING_CASH_FLOW: "operating_cash_flow",
  INVESTING_CASH_FLOW: "investing_cash_flow",
  FINANCING_CASH_FLOW: "financing_cash_flow",
  CAPEX: "capex",
  CASH: "cash",
  DEBT: "debt",
  CURRENT_ASSETS: "current_assets",
  CURRENT_LIABILITIES: "current_liabilities",
  INVENTORY: "inventory",
  SHARES: "shares",
  EPS_DILUTED: "eps_diluted",
  DIVIDENDS: "dividends",
  RD_EXPENSE: "rd_expense",
  SGA_EXPENSE: "sga_expense",
  INTEREST_EXPENSE: "interest_expense",
  TAX_EXPENSE: "tax_expense",
  STOCK_BASED_COMPENSATION: "stock_based_compensation",
  GOODWILL: "goodwill",
  COGS: "cogs",
  ACCOUNTS_RECEIVABLE: "accounts_receivable",
} as const;
